### ISSUE TITLE
Plugin prevents AJAX validation errors from being correctly reported

### ISSUE THREAD

**Issue by bennothommo** [wintercms/wn-ignition-plugin#1]
This plugin appears to prevent the successful handling of AJAX validation errors.

In debug mode, the errors are interpreted as a HTTP 500 error and the Winter-specific messaging is simply injected into the `message` response as a JSON object. When debug mode is turned off, the error seems to simply be rewritten as a "Server Error" message with no specific information about what has occurred.

I haven't used Ignition much so I don't know what in particular it does for handling AJAX exceptions by default, but as a simple solution, we could perhaps defer AJAX exceptions to the Storm exception handler by default.

**Comment by arvislacis** [comment]
Isn't this fixed with the recent commit (https://github.com/wintercms/wn-ignition-plugin/commit/cb09347cf30aa5ce5e7f379d3ad96a7ba25ab486) from @LukeTowers ?

**Comment by LukeTowers** [comment]
It is yes, thanks @arvislacis!
