### ISSUE TITLE
Call to undefined method System\Models\Parameter::hasDatabaseTable()

### ISSUE THREAD

**Issue by iviefistofel** [wintercms/wn-ignition-plugin#6]
BadMethodCallException: Call to undefined method System\Models\Parameter::hasDatabaseTable() in plugins/winter/ignition/middleware/AddWinterContextData.php:19

**Comment by LukeTowers** [comment]
@iviefistofel use the latest develop version of Winter until the next release is pushed out - hopefully soon.
